name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "run cmake "
        run: |
          cd thegreatsitegenerator
          cmake . 
      - name: "run make " 
        run: make 
