name: learn-github-actions
on: [push, pull_request]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "create and enter build dir"
        run: |
          cd thegreatsitegenerator
      - name: "run cmake "
        run: cmake .
      - name: "run make " 
        run: make 
